### ISSUE TITLE
Wrong UEFI detection

### ISSUE THREAD

**Issue by hooddy** [builtbybel/ReadySunValley#10]
I have GA-Z68XP-UD5 board with BIOS on it (not UEFI. I am trying to flash official UEFI but after succeful flash board were glitched and I rollback to BIOS (I am happy it does)).
<img width="869" alt="Compatibility-Screen-Win11-BEAR-PC" src="https://user-images.githubusercontent.com/6899176/124429873-1817ed00-dd77-11eb-9285-ac9cab01f3c2.png">
As well there is typo in UI in Compare section for WhyNotWin11 app name - its missing.

**Comment by Belim** [comment]
Can you check this
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6764078/ReadySunValley_x64.zip) ?

> As well there is typo in UI in Compare section for WhyNotWin11 app name - its missing.

where is the typo?

**Comment by hooddy** [comment]
@Belim i believe there is missed app name "WhyNotWin11".
UEFI detectin bug seems to be still here.

**Comment by Belim** [comment]
hmm, the bug was definitely reproducible...i've tested it now with the fixed version on two machines and its all good here.
are you sure?

i thought the app is called [WhyNotWin11](https://github.com/rcmaehl/WhyNotWin11)?

**Comment by hooddy** [comment]
yep with UEFI all the same.
and yes app is named like this but in your app I see only "App" with no "WhyNotWin11".
Oh wait... is it coz of scaling on my side? So anyway it good to fix.
Anyway thats screen from current version. All the same.
<img width="869" alt="Compatibility-Screen-Win11-BEAR-PC" src="https://user-images.githubusercontent.com/6899176/124484202-d48fa400-ddb3-11eb-99d0-a08152966742.png">

**Comment by Belim** [comment]
Regarding UEFI issue, can you please check this 
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6765754/ReadySunValley_x64.zip) ?

The typo is not an (scaling) issue, the button is just that named :smirk:

**Comment by hooddy** [comment]
this is fixed UEFI issue, now its shows as Legacy.
