### ISSUE TITLE
Wrong SecureBoot detection

### ISSUE THREAD

**Issue by ghost** [builtbybel/ReadySunValley#11]
Disk partition -- wrong (I have 4 HDDs and system one IS GPT);
Secure Boot -- I think for now possibility must be marked for compatibility, not the current state.

**Comment by Belim** [comment]
im with you regarding secure boot. can you test this
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6768328/ReadySunValley_x64.zip) ?
as a result, we now only have supported or unsupported 

the disk partition bug has already been reported here https://github.com/builtbybel/ReadySunValley/issues/7 still have to think about something

**Comment by ghost** [comment]
thanks for the upd, yes secure boot fixed now.

**Comment by Belim** [comment]
regarding the disk partition issues...
if you are interested you can also try the new test build pushed here https://github.com/builtbybel/ReadySunValley/issues/7
