### ISSUE TITLE
Available memory may be incorrectly evaluated.

### ISSUE THREAD

**Issue by XeraanZeel** [builtbybel/ReadySunValley#16]
For me, a 128 GB partition with a little less than 64 GB free space shows up as a problem. However, I believe that Microsoft does not require the free space, but the total size with 64 GB. Also, when hovering the mouse over this problem, no further information is displayed.

**Comment by Belim** [comment]
you're absolutely right. it's just confusing. you don't actually need 64 gb of free space, but just a disk that has a total capacity of 64 gb. from the leaked version of Windows 11, it can be seen that the setup file  size is 4.54 GB. considering that the leaked version does not have all the features, we can say that the actual file size will be between 4.5 to 6 GB.

**Comment by Belim** [comment]
fixed here https://github.com/builtbybel/ReadySunValley/releases/tag/0.23.2

**Comment by XeraanZeel** [comment]
Shows everything correctly for me now. Thanks for your quick response.
