### ISSUE TITLE
WDDM version not recognized properly

### ISSUE THREAD

**Issue by akuropka** [builtbybel/ReadySunValley#19]
Hello,
the check fails due to recognizing WDDM 1.3 instead of 3.0. However, the 3.0 driver is installed...
Btw the notebook has a 17.3 inch display (used as main), second display is 21.5 inch.
Keep up the good work!

![20210710_180315_ReadySunValley_x64](https://user-images.githubusercontent.com/22570574/125169469-91b23f80-e1aa-11eb-839f-bdba3d91efca.png)

![20210710_180802_dxdiag](https://user-images.githubusercontent.com/22570574/125169480-a098f200-e1aa-11eb-83d5-9f26108e547e.png)

**Comment by Belim** [comment]
hey, 
can you check this 
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6795745/ReadySunValley_x64.zip) ?  :smiley:

**Comment by Belim** [comment]
btw, did you maybe use the app instance including dxv.txt file from another machine? please delete the dxv.txt file and run a fresh check... versioning of wddm must work 😁

**Comment by akuropka** [comment]
![20210711_150748_dwm](https://user-images.githubusercontent.com/22570574/125196382-0b553680-e25a-11eb-83dc-aa18919f1876.png)
![20210711_150819_ReadySunValley_x64](https://user-images.githubusercontent.com/22570574/125196393-1314db00-e25a-11eb-89e1-5bc9177c101b.png)
Started directly out of zip anywhere test it anywhere before. Result is the same.
Btw it hangs for some time inbetween and writes initially that no TPM is found.

**Comment by Belim** [comment]
please upload your dxdiag config as txt-file.

**how-to**
https://support.microsoft.com/en-us/windows/open-and-run-dxdiag-exe-dad7792c-2ad5-f6cd-5a37-bf92228dfd85

> Btw it hangs for some time inbetween and writes initially that no TPM is found.

i am amazed at this. you have a super machine :grin: 
the hangup comes from reading the dxdiag information. i wonder how big the file actually is now. it should not weigh more than 100 kb normally

**Comment by akuropka** [comment]
Indeed the progress bar of DxDiag takes some time... ~7-8 seconds, fits with your app.
[DxDiag.txt](https://github.com/builtbybel/ReadySunValley/files/6798328/DxDiag.txt)

**Comment by Belim** [comment]
I have fed your dxdiag file on my machine  and the readout of wddm 3.0 works flawlessly
![ReadySunValley_Trb9ohFxsb](https://user-images.githubusercontent.com/57478606/125237887-af84bf00-e2e6-11eb-8946-0f581f8d1b1c.png)

please open the `dxv.txt` file generated by ReadySunValley (its in the install directory of app itself) and search for "Driver Model:" and check if the version wddm 3.0 is really noted here

Do you use the 64 bit version of ReadySunValley? if so, then check again with this version that explicitly takes the 64-bit
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6798891/ReadySunValley_x64.zip)
 version of dxdiag

**Comment by akuropka** [comment]
[dxv.txt](https://github.com/builtbybel/ReadySunValley/files/6799245/dxv.txt)
I'm no specialist of reading those details but there is one time 1.3 (which is a duplicate of the later one?) and twice 3.0.

I used the x64 version...

**Comment by Belim** [comment]
you have to graphic cards installed

ReadySunValley gets the first gpu and its an UHD Graphics 620 with wddm 1.3. this is the right one as it is your primary gpu

the second occurrence of wddm version 3.0 is incorrect anyway. it does not report the DDI Version  (unknown) and this is the version your display driver is using
you can check this two lines
```
DDI Version: Unknown
Feature Levels: Unknown
```
the third occurrence of wddm 3.0 is for your second integrated gpu here an NVIDIA GeForce 930MX.
currently there is no check of more than one gpu. maybe i will add something in a future version but currently there is no fix for this

**Comment by akuropka** [comment]
Both are compatible and have 3.0 drivers installed. Don’t know what’s wrong, just wanted to bring this to your attention…
