### ISSUE TITLE
Download latest Nightly/testing build!

### ISSUE THREAD

**Issue by Belim** [builtbybel/ReadySunValley#20]
**If something does not work and a testbuild is provided, it can now be downloaded here**

**DOWNLOAD** 
Version from: July 18, 2021 18:00 PM
_No testing release available_

**Issues Addressed in latest release**
- New application icon (thanks to [Oleg Chashko](https://github.com/Oleg-Chashko))
- Improved storing application data (now under LocalAppDataDir\Packages\36220Builtbybel.ReadySunValley_k6hq5jrzcagm8\Settings)
- Removed support for getting a second opinion with utility WhyNotWin11 https://github.com/builtbybel/ReadySunValley/issues/18 https://github.com/builtbybel/ReadySunValley/issues/34
- Refactored Inet connectivity check
- Improved OS detection https://github.com/builtbybel/ReadySunValley/issues/33
- Fixed several localization bugs
- Updated Japanese localization https://github.com/builtbybel/ReadySunValley/pull/35
- UI Improvements

_Please note that you will have to update testing releases manually to latest stable release_

**Comment by pklion** [comment]
Is this timestamp UTC?
