### ISSUE TITLE
ReadySunValley does crash on ASUS Sabertooth X99 W10 x64 21H1

### ISSUE THREAD

**Issue by 100PIER** [builtbybel/ReadySunValley#21]
I have tried ReadySunValley on ASUS Sabertooth X99 machine (with no TPM v2.0 chipset plugged into the TPM-L 20-pin on board connector) and got a crash. See attached file.
WhyNotW11 tool does not crash on the same PC.
W11.Compatibility.Checker tool does not crash on the same PC.

![RSV_bug_11juillet21](https://user-images.githubusercontent.com/45947394/125188891-d505c000-e235-11eb-8880-32a3110bf55f.PNG)

**Comment by Belim** [comment]
can you please try the latest test build here https://github.com/builtbybel/ReadySunValley/issues/20
if the directx/wddm check really stops (looks like it on the screen), this version will give me more information

can you also maybe try a previous release, e.g. https://github.com/builtbybel/ReadySunValley/releases/tag/0.23.3

**Comment by 100PIER** [comment]
Belim, Thanks,  with the latest test build the crash is now fixed !
Screenshot attached.
Many thanks for your very quick support.

![RSV_bug_fixed_new_release_11juillet21](https://user-images.githubusercontent.com/45947394/125192265-37b38780-e247-11eb-81e1-f890995459c7.PNG)
