### ISSUE TITLE
Update file README.md

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#24]
After changes in the interface, don't forget to update the file README.md
<img width="1241" alt="Screen Shot 2021-07-12 at 16 16 44" src="https://user-images.githubusercontent.com/62497891/125303156-e2ea3c80-e32c-11eb-81ee-3c4ab3ef3f0d.png">

**Comment by Belim** [comment]
just a a perfectionist 😁

**Comment by Oleg-Chashko** [comment]
> just a a perfectionist 😁

Yes, that's my character. 😁
