### ISSUE TITLE
Typos in the code

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#25]
Misprints in the code in English. Ich habe dein Deutsch nicht überprüft. Ich denke, dein Deutsch perfekt ist.
<img width="910" alt="Screen Shot 2021-07-12 at 16 13 18" src="https://user-images.githubusercontent.com/62497891/125312599-b76b5000-e334-11eb-863a-4dbec5dbe0a3.png">
<img width="1171" alt="Screen Shot 2021-07-12 at 16 30 47" src="https://user-images.githubusercontent.com/62497891/125312611-bafed700-e334-11eb-8cd4-edd77fc512ed.png">
<img width="1171" alt="Screen Shot 2021-07-12 at 16 34 42" src="https://user-images.githubusercontent.com/62497891/125312618-bcc89a80-e334-11eb-82e6-6f98636c0b42.png">
<img width="1123" alt="Screen Shot 2021-07-12 at 16 37 28" src="https://user-images.githubusercontent.com/62497891/125312625-be925e00-e334-11eb-8c70-8eb079aac95a.png">
<img width="854" alt="Screen Shot 2021-07-12 at 16 46 10" src="https://user-images.githubusercontent.com/62497891/125312633-bfc38b00-e334-11eb-8122-58c7318d95dd.png">
<img width="854" alt="Screen Shot 2021-07-12 at 16 47 52" src="https://user-images.githubusercontent.com/62497891/125312641-c225e500-e334-11eb-91a7-f3ba719a3cb5.png">
<img width="854" alt="Screen Shot 2021-07-12 at 16 48 55" src="https://user-images.githubusercontent.com/62497891/125312652-c3efa880-e334-11eb-99c4-78260b388ba6.png">
<img width="854" alt="Screen Shot 2021-07-12 at 16 49 58" src="https://user-images.githubusercontent.com/62497891/125312661-c5b96c00-e334-11eb-9915-d6dbe46b1b06.png">
<img width="854" alt="Screen Shot 2021-07-12 at 16 59 56" src="https://user-images.githubusercontent.com/62497891/125312673-c7832f80-e334-11eb-9edf-6d1ae4efbdd4.png">

**Comment by Belim** [comment]
damn, how many eyes do you have 😁  but that's how software testers are, i know a few

**Comment by Belim** [comment]
will review this tomorrow 😭

**Comment by Oleg-Chashko** [comment]
Happy to help😁, there are some typos in the code with extra spaces and code formatting.
But it does not affect the work of the code.

**Comment by Belim** [comment]
hope nothing is overlooked 😁 
https://github.com/builtbybel/ReadySunValley/releases/tag/0.40.0

unfortunately i only have two eyes
