### ISSUE TITLE
Improve the behavior of the program loading indicator (WhyNotWin11)

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#26]
1. Gradual and smooth filling of the loading bar with color. 
2. At the end of the download, the caption (Launch of the WhyNotWin11 program).
3. Please remove artifacts when the download is complete.

At the moment: The video is slowed down in 2 times (for easy study of the process).

https://user-images.githubusercontent.com/62497891/125618556-ea4620f4-72ea-4b44-af11-915f4c469e1c.mp4

**Comment by Belim** [comment]
video is still too fast 🤣 

> 1. Gradual and smooth filling of the loading bar with color.

the color of the pbar could be changed, but which one do you have in mind? its not more than just a game


> 2\. At the end of the download, the caption (Launch of the WhyNotWin11 program).

you mean a prompt to launch the app?


> 3\. Please remove artifacts when the download is complete.

killing this msgbox? 😢 
![ReadySunValley_ZJZqbJ1pNv](https://user-images.githubusercontent.com/57478606/125610923-5450de74-b825-40a6-ba96-29549a98b1db.png)

**Comment by Oleg-Chashko** [comment]
_Video is still too fast_ -> Increased the time to 1 minute. :)

_1. The color of the p-bar could be changed, but which one do you have in mind? It's not more than just a game._ -> That's not what I meant. I know that. 
Filling (animation of the process), is the movement of the green bar to the right side, should be slow (so prettier), not at warp speed of the starship Enterprise. :)

Example: Progress-bar
![tenor](https://user-images.githubusercontent.com/62497891/125622512-031b66e9-98c0-4890-90d1-f2940ca6d0b5.gif)

_2. You mean a prompt to launch the app?_ -> Yes

_3. Killing this msgbox?_ -> No
Please remove artifacts when the download is complete. In the video, the red arrows indicate artifacts.

**Comment by Belim** [comment]
i can embellish the animation a bit but i don't want to put a lot of energy into this for a temporary feature

**Comment by Oleg-Chashko** [comment]
> i can embellish the animation a bit but i don't want to put a lot of energy into this for a temporary feature

Is it possible to delete it? The animation looks incomplete. Do it as you see fit.

**Comment by Belim** [comment]
what about this https://github.com/builtbybel/ReadySunValley/issues/20 ? a bit smoOOooooother

**Comment by Oleg-Chashko** [comment]
It's noticeably better😀. You can close the topic.
