### ISSUE TITLE
Embed localization files in the executable file

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#27]
Please embed the localization files in the executable.
<img width="817" alt="Screen Shot 2021-07-13 at 15 48 46" src="https://user-images.githubusercontent.com/62497891/125502540-26f797ad-2331-4279-8916-5181aa452c55.png">

**Comment by Belim** [comment]
this is a problem for me. the exe will grow the more localizations we have and i want to avoid that.

but you could outsource the localizations and make them optional for download. what do you think?

**Comment by Oleg-Chashko** [comment]
> this is a problem for me. the exe will grow the more localizations we have and i want to avoid that.
> 
> but you could outsource the localizations and make them optional for download. what do you think?

1. When starting the program, offer a list of languages, and if the user chooses, download it from the Internet and run the program with this localization.
- What if there is no connection to the Internet?
- Should we make the code more complicated?

It is easier to build it into an executable file. The size of your localization file is very small. Apply compression.

**Comment by Belim** [comment]
> > this is a problem for me. the exe will grow the more localizations we have and i want to avoid that.
> > but you could outsource the localizations and make them optional for download. what do you think?
> 
> 1. When starting the program, offer a list of languages, and if the user chooses, download it from the Internet and run the program with this localization.
> 
> * What if there is no connection to the Internet?

no win11 😁  the language file for ReadySunValley is not needed then either

> * Should we make the code more complicated?

i like it 😁 um...sometimes
> 
> It is easier to build it into an executable file. The size of your localization file is very small. Apply compression.

i would suggest to continue like this until we don't have some more localizations on board. if there should be more than 10, then we should think about something.

**Comment by Oleg-Chashko** [comment]
1. What if there is no connection to the Internet? -> no win11 😁 the language file for ReadySunValley is not needed then either:

Example:

_Well, if you don't have an Internet connection you can't really download this app though._
That's an option you didn't consider?
What makes you think I downloaded it from the Internet. An acquaintance gave it to me on a usb flash drive.

_Are you sure that all the computers where Windows 11 will be installed will be connected to the Internet?_
I'm not so sure about that.

_Yes, and then you also got windows 11 bootable usb?_
As surprising as this may sound. But, I keep all the software on my server. And I update, on a daily basis, images of Linux, Windows, MacOS, etc. And I exchange a lot, via USB flash.

_I understand your point, but there is such low probability of that!_
It depends on what country you live in and whether it is a city or a village. Some residents are only connected to ADSL, and some have only 3G. If you and I do not have problems with the Internet, it does not mean that others do not have them too.

I will say this, I am in Germany and here in some villages there is no wired Internet and no mobile normal, people have to go up the mountain to make a call. Deutsche Telekom does not want to install cable because it is not profitable. There is a private satellite Internet for the whole village. With a gigabyte fee for Internet traffic.

Unfortunately, people are not forward-thinking. Often they think that if they have something, then everyone has it too. And if he knows and understands it, then all other people should know and understand it. Unfortunately, this is a big misconception.

2. Should we make the code more complicated? -> I like it 😁 um...sometimes -> 
The longer the code, the more errors and the larger the application. And you said that language files will increase the size of the program. Strange paradox, you don't feel sorry for the extra code, but you feel sorry for the language files?

3. As for localization: I can localize the Ukrainian and Russian, but I do not see the point. Since residents of Ukraine and Russia prefer the software in English. And even if the program has the Ukrainian or Russian language, people prefer to switch to English. Such a paradox.😁

**Comment by Oleg-Chashko** [comment]
Closed the discussion, if necessary, you can reopen it.
