### ISSUE TITLE
File (dxv), should not appear, next to the executable file

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#28]
Please make it so that: the file (dxv), must appear, in the Temp folder. And after restarting the used file, the old version in the Temp folder must be replaced by the new file (dxv).
<img width="817" alt="Screen Shot 2021-07-13 at 15 48 46 2" src="https://user-images.githubusercontent.com/62497891/125503853-484a2a66-2e56-43b0-a4cb-9db39acf36d7.png">

**Comment by Belim** [comment]
a good one 😃 
please check if its working as expected https://github.com/builtbybel/ReadySunValley/issues/20

**Comment by Oleg-Chashko** [comment]
Great, it worked out!
This topic can be closed 😃
<img width="709" alt="Screen Shot 2021-07-13 at 21 44 35" src="https://user-images.githubusercontent.com/62497891/125515707-aa66b14c-e706-4c90-b6b9-ae002747accc.png">
