### ISSUE TITLE
Errors when there is no internet connection

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#29]
Errors when there is no internet connection.

<img width="233" alt="Screen Shot 2021-07-13 at 20 53 16" src="https://user-images.githubusercontent.com/62497891/125510075-d359f3c0-a00f-4c30-bb09-84b2a76435f4.png">

**Log file:**
[Log.txt.zip](https://github.com/builtbybel/ReadySunValley/files/6811313/Log.txt.zip)

**Video:**

https://user-images.githubusercontent.com/62497891/125510199-92e0b27b-b31d-41a6-9912-16f29a3ea9b6.mp4

**Comment by Belim** [comment]
should be fixed in latest test build

**Comment by Oleg-Chashko** [comment]
> should be fixed in latest test build

:( 

https://user-images.githubusercontent.com/62497891/125616817-6a3ad97e-1389-4f31-8678-fa85ac829e36.mp4


https://user-images.githubusercontent.com/62497891/125616846-632e1e3a-1db8-4222-a31d-d4262be47c24.mp4

**Comment by Belim** [comment]
yeah, im a bit lazy for new locailzation strings and using some verbose output 😬 
so a stack trace message would be understood by humans (you, me, devs) 
but i think that for the normalo user more understandable messages is needed 🤔

**Comment by Oleg-Chashko** [comment]
_But i think that for the normal user more understandable messages is needed 🤔_
I completely agree with you. :)

**Comment by Belim** [comment]
some things have gotten better in the latest test build https://github.com/builtbybel/ReadySunValley/issues/20

**Comment by Oleg-Chashko** [comment]
Problem solved, the topic can be closed. :)
But another problem appeared, with the interface. :(

**Comment by Belim** [comment]
totally impossible

**Comment by Oleg-Chashko** [comment]
> totally impossible

With the Internet turned off. The English localization now has the German language.

**Comment by Belim** [comment]
😬 wrong localization file. many thanks 💯

**Comment by Oleg-Chashko** [comment]
I apologize very much for being off topic, after your answer I will delete the question. Question: why did you make it possible to download the program (WhyNotWin11), (I am also involved in this project). Do you think your program is worse? And your program needs help from the program (WhyNotWin11)? 
I think that your program is no worse than others.

**Comment by Belim** [comment]
something similar has been asked here https://github.com/builtbybel/ReadySunValley/issues/18

before you undergo surgery, do you get a second opinion or not?
four eyes always see more than two. i don't even like the app mentioned but it is the only known alternative since the pc health check app is temporarily removed by microsoft. 

we'll see how it goes with ReadySunValley and i can assure you it is even the better app

**Comment by Oleg-Chashko** [comment]
I will say this I have two eyes :), but the problem is not in the number of eyes :), but how to use them (it all depends on the mindset). From languages I like Assembler and the whole family of C.

_We'll see how it goes with ReadySunValley and i can assure you it is even the better app_ -> I don't doubt that.

**Comment by Belim** [comment]
um.., you are not one of the devs of whynotw11?

**Comment by Oleg-Chashko** [comment]
> um.., you are not one of the devs of whynotw11?

No. 
<img width="394" alt="Screen Shot 2021-07-14 at 23 49 58" src="https://user-images.githubusercontent.com/62497891/125697752-b4ca6b64-d73b-4290-9526-9b0356980ec7.png">

**Comment by Oleg-Chashko** [comment]
I just help them for fun, and not only them.

**Comment by Belim** [comment]
um, you are the second according to statistics 😁

**Comment by Belim** [comment]
fixed

**Comment by Oleg-Chashko** [comment]
> um, you are the second according to statistics 😁

I cleaned the code, and the two localizations.
