### ISSUE TITLE
Storage fails test with 1.1TB free, app still says it's compatible

### ISSUE THREAD

**Issue by rock3r** [builtbybel/ReadySunValley#30]
![Compatibility-Screen-Win11-DESKTOP-QCEPJ6I](https://user-images.githubusercontent.com/153802/125623116-ed2f9aa1-88eb-4887-a4da-b394bba324df.png)

App v0.40.0

**Comment by Belim** [comment]
can you check latest testing release https://github.com/builtbybel/ReadySunValley/issues/20 ?

**Comment by rock3r** [comment]
Looks the same I'm afraid :(

![image](https://user-images.githubusercontent.com/153802/125679445-cef26248-8589-44c8-9727-f4ba6fd20d67.png)

**Comment by Belim** [comment]
damn had not uploaded the version with the fix 😬 
now its online https://github.com/builtbybel/ReadySunValley/issues/20

**Comment by rock3r** [comment]
![image](https://user-images.githubusercontent.com/153802/125683743-662ff97f-2fe5-47e1-b43d-9faed0a3122d.png)

That works :)
