### ISSUE TITLE
Improved CPU Compatibility detection

### ISSUE THREAD

**Issue by Belim** [builtbybel/ReadySunValley#32]
check latest testing build https://github.com/builtbybel/ReadySunValley/issues/20 and give feedback

- moved all supported cpus (intel, amd, qualcomm) into one resource file
- maybe a milisecond faster detection Using StreamReader.ReadLine!?
- reference file generated in output dir of app (temp dir, localappdir?)

**Comment by Oleg-Chashko** [comment]
- _moved all supported cpus (Intel, AMD, Qualcomm) into one resource file_ -> If, you are comfortable with that, it's a good idea.
- _maybe a millisecond faster detection Using StreamReader.ReadLine!?_ -> If, you are comfortable with that, it's a good idea. I didn't notice the difference. :)
- _reference file generated in output dir of app (temp dir, localappdir?)_ -> In the future, this File should be in the temp folder. Where the file "(dxv)-> (rsv)" is now in the temp folder.

Fixed (corrected) File "supportedCPU" (Microsoft made typos in the names of processors). I corrected the same Microsoft errors in another project.

[Fixed_supportedCPU.zip](https://github.com/builtbybel/ReadySunValley/files/6822576/Fixed_supportedCPU.zip)

**Comment by Belim** [comment]
for reference i will push the file within the app install directory. some would like to know how the matching is made.

i have also thought about an online sync, but you once told me that not everyone has internet or good internet, so discarded that again 😄

**Comment by Belim** [comment]
many thanks for the fixed file version 🤝 💯

**Comment by Oleg-Chashko** [comment]
> many thanks for the fixed file version 🤝 💯

Glad to have helped.😄

**Comment by Oleg-Chashko** [comment]
_for reference i will push the file within the app install directory. some would like to know how the matching is made._ 

How to do it right: this file (supportedCPU) should be in the temp folder. And if the user wants to see compatible processors, he clicks the button in your program, a window opens and in a clear form displays **Processors** and **Graphics cards** that are compatible with Windows 11. 

The same thing I suggested in another project.

P.S.: Try to regroup from the silly ideology of Windows. (Clutter up with files, all the space around you.) :(

**Comment by Oleg-Chashko** [comment]
I moved my suggestions for improvement to the topic "Improving the user interface".
If you want, can you close this topic.

**Comment by Belim** [comment]
yep, let's get here going https://github.com/builtbybel/ReadySunValley/issues/22

**Comment by epman100** [comment]
> 
> 
> check latest testing build #20 and give feedback
> 
>     * moved all supported cpus (intel, amd, qualcomm) into one resource file
> 

needs another update as MS recently added a few more supported Intel CPUs (a few 7th gen Intel processors) as noted by [this MS blog published Aug. 27](https://blogs.windows.com/windows-insider/2021/08/27/update-on-windows-11-minimum-system-requirements-and-the-pc-health-check-app/)

"We did identify a set of PC models that meet the principles while running on Intel 7th Gen processors that we did not originally include in our minimum system requirements."
