### ISSUE TITLE
Wrong definition: OS Windows 11

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#33]
https://user-images.githubusercontent.com/62497891/125925969-5cf532a4-3d1c-4267-8a29-b822316a230c.mp4

**Comment by Belim** [comment]
can you check value  of `ProductName ` in this hive `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion` ?

**Comment by Oleg-Chashko** [comment]
<img width="1112" alt="Screen Shot 2021-07-16 at 14 53 35" src="https://user-images.githubusercontent.com/62497891/125951822-0bed43fd-283b-43bf-9131-5ce479fa12bd.png">

**Comment by Oleg-Chashko** [comment]
<img width="794" alt="Screen Shot 2021-07-16 at 20 16 56" src="https://user-images.githubusercontent.com/62497891/125991741-43e585ba-cf05-4814-a229-a1b3e383030f.png">

[rsv.txt.zip](https://github.com/builtbybel/ReadySunValley/files/6832633/rsv.txt.zip)

**Comment by Belim** [comment]
this has not yet been adjusted system-wide by microsoft. the registry entry should also be correct for the official release. let us close it for the first

**Comment by Oleg-Chashko** [comment]
> this has not yet been adjusted system-wide by microsoft. the registry entry should also be correct for the official release. let us close it for the first

I figured as much, I agree we'll close, we'll see in the spring.
