### ISSUE TITLE
Question: do I need a third-party app (WhyNotWin11)?

### ISSUE THREAD

**Issue by Oleg-Chashko** [builtbybel/ReadySunValley#34]
**I warn you at once! I will communicate as a regular user (us 99%).**
I downloaded your program yesterday. I ran it, and I see that my computer has DirectX 12. Then I clicked some button in your program. A new window opened and I see that my computer doesn't have DirectX 12. Question is your program itself does not know if it has DirectX 12 or not. And what should I believe, it seems your program does not work quite right. I will go on the internet to look for a better program than yours.

That's the kind of thing that will happen, and not just one. And this test is only on one computer. With more computers and their configurations there will be even more discrepancies.
<img width="1384" alt="Screen Shot 2021-07-16 at 12 47 07" src="https://user-images.githubusercontent.com/62497891/125941400-9b3a76b3-c0fa-4734-afdf-623d5cba5e69.png">

P.S.:
I'm sorry, but I don't understand this sacred meaning, the integration of downloading a third-party application.

**Comment by Belim** [comment]
ReadySunValley is right? have I understood correctly 😬

**Comment by Belim** [comment]
I see your point, many opinions, different results .. 🤔

**Comment by Oleg-Chashko** [comment]
> ReadySunValley is right? have I understood correctly 😬

YES, that's it! 
That's what I don't understand! Why did you build in, this application, what's the secret?

**Comment by Belim** [comment]
there are no mysteries at all 😁  the reason is really just, that i wanted to give everyone the opportunity to compare the result. I thought it was a nice to have feature as no program can be relied on one hundred percent ...on the other hand, i really don't like the technical part of the program at all. 

i am currently trying to push ReadySunValley to the Microsoft App Store. If that works, WhyNotW11 is out.

**Comment by Oleg-Chashko** [comment]
> I see your point, many opinions, different results .. 🤔

YES, Moreover, the result in a third-party program is worse than in your program. Are you getting paid to promote another program?

**Comment by Belim** [comment]
> > I see your point, many opinions, different results .. 🤔
> 
> YES, Moreover, the result in a third-party program is worse than in your program. Are you getting paid to promote another program?

of course not. i don't earn a cent on anything. i have mentioned the reason above.

**Comment by Oleg-Chashko** [comment]
It's like cheating in school, from another student's notebook. You know that he is not a good student. 0_o

**Comment by Oleg-Chashko** [comment]
> > > I see your point, many opinions, different results .. 🤔
> > 
> > 
> > YES, Moreover, the result in a third-party program is worse than in your program. Are you getting paid to promote another program?
> 
> of course not. i don't earn a cent on anything. i have mentioned the reason above.

Sorry, I didn't see the answer.

**Comment by Oleg-Chashko** [comment]
Sorry, I didn't mean to offend you.

**Comment by Belim** [comment]
it's all good  everything is going in the direction of removing this feature 🤔 
i thought you would support the project!? you should be happy if both projects are under the same umbrella 😁

**Comment by Oleg-Chashko** [comment]
I support both projects equally, for me they are equal. But the final point, for which it is necessary to fight, is the result. And in this your project, the best and I try to show you this. But I'll tell you the truth, I personally will not use either project. This is a paradox.😁

**Comment by Oleg-Chashko** [comment]
_i thought you would support the project!? you should be happy if both projects are under the same umbrella 😁_
When they improve each other, I'm all for it, but when they duplicate and degrade, categorically not, I'm against it.

**Comment by Oleg-Chashko** [comment]
And if Microsoft cancels its "innovation", I'll laugh at it all. Plus, there will be 100% official versions without TPM.
Because Microsoft is not consistent in their actions and words. If Microsoft said something, it could change tomorrow at Microsoft.

**Comment by Oleg-Chashko** [comment]
Closed the topic, the issue is resolved.
