### ISSUE TITLE
Storage check fails if HDD size is in TB

### ISSUE THREAD

**Issue by torum** [builtbybel/ReadySunValley#4]
Hello! Thank you for the nice tool.

My system has 1.8 TB of hard disk. 

In the MainWindow.cs, GetTotalFreeSpace(systemdrive) returns something like 1986661847040, and FormatBytes(systemfreespace) returns 1.8.

So,
if (systemspacedouble >= 64)
fails for TB. I think...

![2021-07-01 223345](https://user-images.githubusercontent.com/37834607/124135617-f391eb80-dabe-11eb-8f33-651577276112.jpg)

**Comment by Belim** [comment]
can you please check latest release
https://github.com/builtbybel/ReadySunValley/releases/tag/0.11.6

**Comment by torum** [comment]
yes, it looks OK now.
