### ISSUE TITLE
ReadySunValley Hungarian translate

### ISSUE THREAD

**Issue by gidano** [builtbybel/ReadySunValley#48]
Hello,
I've created the Hungarian language file, I would like to offer.
Unfortunately, I don't understand the Pull request or the fork.
I hope you find it useful... :)

**Comment by Belim** [comment]
thanks, will be included in upcoming release 😃

**Comment by Belim** [comment]
can you please provide the not compiled resx file?

**Comment by gidano** [comment]
I don't have a resx file, the translation is based on "de" ReadySunValley.resources.dll.

**Comment by Belim** [comment]
this won't work.
but how did you translate the strings? or did you just rename the dll file?

you need to translate the following [file](https://github.com/builtbybel/ReadySunValley/blob/main/src/RSV/Locales/Locale.resx) completely and provide me the resx file. here is a how-to https://github.com/builtbybel/privatezilla/wiki/Translate

**Comment by gidano** [comment]
I was unable to read the submitted .resx file with Resx Translator without error.
That’s why I renamed it to a .html extension, edited the content to be translated, and the extension became .resx again.
I checked the .html in a browser, I saw the same as on the GitHub site. That's why I think it's appropriate, of course, and then you can tell. It was a good little relaxation for Sunday afternoon...

**Comment by Belim** [comment]
> That’s why I renamed it to a .html extension, edited the content to be translated, and the extension became .resx again.

😿 

 it won't work that way. no we have an html file
```
<!DOCTYPE html>
<html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">
 <head>
```

i need the unformatted resx file

**Comment by gidano** [comment]
Hello Belim,
I've created the Hungarian language file, I would like to offer.
I hope you find it useful... :)
There is no .resx file, but you get the complete language .dll file, you just have to copy it to the release folder! :)
I am glad to have been able to contribute to the project. In the uploaded folder you will also find photos of the Hungarian language interface!

[ReadySunValley_x64.HU.language.zip](https://github.com/builtbybel/ReadySunValley/files/6988046/ReadySunValley_x64.HU.language.zip)
