### ISSUE TITLE
the Windows11 's new requirements

### ISSUE THREAD

**Issue by sky5454** [builtbybel/ReadySunValley#53]
pc health check
![image](https://user-images.githubusercontent.com/12370628/135957799-0cf86b3c-63a9-4abb-8635-416235c6312f.png)

you can see the main problem is the unsupported CPU but not the TPM.

and for the `insider build 22000.194`, after this version, Microsoft would not support the old CPU.
![image](https://user-images.githubusercontent.com/12370628/135958134-47c3ac45-7b1a-4454-8e36-02266bb2653c.png)
see: https://blogs.windows.com/windowsexperience/2021/07/15/introducing-the-next-feature-update-to-windows-10-21h2/

**Comment by Belim** [comment]
https://github.com/builtbybel/ReadySunValley/releases/tag/0.70.0
