### ISSUE TITLE
Drive detection

### ISSUE THREAD

**Issue by coder66** [builtbybel/ReadySunValley#6]
My Surface 5 Pro with micro SD card shows that the boot drive has MBR, this is incorrect.

SD card is drive D, the Windows and boot drive is C

When I remove the SD card, the result is correct. The test should ignore other drives besides the primary boot.

![photo_2021-07-02_14-26-26](https://user-images.githubusercontent.com/14278231/124274458-93905900-db41-11eb-8055-1521f52279c3.jpg)
![photo_2021-07-02_14-27-02](https://user-images.githubusercontent.com/14278231/124274460-93905900-db41-11eb-82b4-17011df5aedd.jpg)

**Comment by Belim** [comment]
can you please check this one...now it should only look for the bootpartition
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6754918/ReadySunValley_x64.zip)

**Comment by coder66** [comment]
Works perfectly, it now correctly ignores the other drive.

**Comment by Belim** [comment]
would not have noticed this :nerd_face: ..thanks for reporting  :grin:

**Comment by coder66** [comment]
To be honest, I think the MS tools and telemetry also do not detect this correctly as they kicked me out of the Beta Insider program and pushed my PC into release preview, although it passes all the tests.......

Thanks for the quickfix 👍 💯

**Comment by Belim** [comment]
it's kind of funny that redmond - the multi-billion group can't get a kindergarten app like PC Health Check to work properly, but an operating system that somehow just works :grimacing: :laughing:

**Comment by coder66** [comment]
> 
> 
> it's kind of funny that redmond - the multi-billion group can't get a kindergarten app like PC Health Check to work properly, but an operating system that somehow just works 😬 😆

Too big to fail ;-)
