### ISSUE TITLE
"Disk Partition Type" check fails, if one drive is MBR formatted [not the main drive]

### ISSUE THREAD

**Issue by Aris-t2** [builtbybel/ReadySunValley#7]
Hi,
thanks for this nice tool.

I came across a small issue. One non-GPT formatted drive causes the whole "Disk Partition Type" check to fail.

There are 4 SSDs inside my PC and one is indeed MBR formatted, but it is not the main drive, so ReadySunValley should not even check that, should it? From my understanding Win 11 check tools should only check the main drive (the one Windows is running on) or am I wrong?

1. Samsung SSD 970 Pro 1TB M2 (GPT formatted) [Win 10 / drive C]
2. Samsung SSD 960 EVO 1TB SATA (GPT formatted)
3. Samsung SSD 960 EVO 1TB SATA (GPT formatted)
4. Samsung SSD 840 Pro 128GB SATA (MBR formatted)

![image](https://user-images.githubusercontent.com/6013569/124346468-3ea32000-dbdf-11eb-878d-1cd6d9cabee2.png)

**Comment by Belim** [comment]
hi, 
curious about this one. it should only look for active/boot partitions

Can you check this one
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6758107/ReadySunValley_x64.zip)
partitions.

**Comment by Belim** [comment]
hi, 
curious about this one. it should only look for active/boot partitions

Can you check this
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6758115/ReadySunValley_x64.zip)

**Comment by Aris-t2** [comment]
I forgot to tell the MBR one is also a boot partition with an alternative Win 10 OS/setup used as a backup, but it is not the active one. 

Same result as before:
![image](https://user-images.githubusercontent.com/6013569/124349842-9f3b5880-dbf1-11eb-9e4a-4f877e1e11bc.png)

**Comment by Belim** [comment]
I assume your system disk has not the index 0 ?

So my assumption about the wmi bootpartition property usage is incorrect for cases when bootmanager is on another disk. I thought the OS uses the active partition (with index 0) when booting from a hard disk.

Hmm, i dont know how WMI could now tell me which one is the active partition :thinking:

**Comment by Aris-t2** [comment]
You are right, the current system disk has index 3, while the "old" backup disk with MBR has index 0.
So the check for index 0 causes the issue.

Actually there is no classic boot manager on any drive, since I temporarily removed the SATAs when I installed the OS on on the M2. When needed I use the UEFI/BIOS/motherboard boot manager.

**Comment by Belim** [comment]
Can you check this 
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6794802/ReadySunValley_x64.zip) ?
Please check also the "List all" linklabel and tell me whether all partitions has been detected

**Comment by Aris-t2** [comment]
Sure, thanks for looking into this. Current result:

![image](https://user-images.githubusercontent.com/6013569/125158615-84795e80-e172-11eb-8a82-2135e7d44303.png)

**Comment by Aris-t2** [comment]
I'm not sure there is a way to change the disk index of a drive, but I think the test/check can always return valid, if the drive the system is on offers GPT.

Something like this (sorry for the pseudo code, but I think you get my idea):

```css
var result_system_gpt = false;

for(i=0;i<=DiskIndex.length-1;i++) {
  for(j=0;j<=PartitionIndex.length-1;j++) {
    if (DiskIndex[i].PartitionIndex[j].GPT=="System")
      result_system_gpt = true;
      return;
  }
}
```

**Comment by Belim** [comment]
> if the drive the system is on offers GPT. Something like this (sorry for the pseudo code, but I think you get my idea):

do it exactly like this but it does not work :grin:

now it only checks for Bootpartition and GPT occurrences. Can you check this
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6795162/ReadySunValley_x64.zip)

**Comment by Aris-t2** [comment]
![image](https://user-images.githubusercontent.com/6013569/125164171-345dc480-e191-11eb-8e44-c544ee8e8f87.png)

**Comment by Belim** [comment]
another attempt 
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6795465/ReadySunValley_x64.zip)

**Comment by Aris-t2** [comment]
Thanks for looking into this.

![image](https://user-images.githubusercontent.com/6013569/125168470-046cec00-e1a6-11eb-83d9-db919b730e37.png)

**Comment by Belim** [comment]
damn, thats not possible. it loops through all partitions and stops at the first one that offers gpt support. I have tested on two systems and it works here

> Samsung SSD 970 Pro 1TB M2 (GPT formatted) [Win 10 / drive C]

does this disk have index 3 and is also the boot partition?

**Comment by Aris-t2** [comment]
Looks like converting my SSD using mbr2gpt back then created a weird result, maybe even too much partitions?
Disk index 3 has four partitions.

According to the above screenshot the system is on partition 3, but looking into "disk management utility" (not sure, what the exact name is on English OS), tells the system is on partition 2. Anyway the system partition is also the boot partition, called "Startpartition" in the screenshot below.

![image](https://user-images.githubusercontent.com/6013569/125175917-ba98fb80-e1cf-11eb-881a-a3c65ab7462c.png)

**Comment by Aris-t2** [comment]
Looks like this can be closed now. Good job.

![image](https://user-images.githubusercontent.com/6013569/125195415-c7f8c900-e255-11eb-8191-e0e1341ecb0d.png)

**Comment by Belim** [comment]
hooray! ich nehme an, der screen ist mit dem gestrigen release 0.30  geschossen... die ersten beiden sind mbr formattiert und deine  systempartition mit index3 wird richtig erkannt!?

aus der wmi funktion werde ich aber nicht schlau. sowohl die suche nach "System" als auch "BootPartition=True" habe ich weggelassen und es scheint wohl richtig zu funkt. 

eine schwere geburt, aber danke für die unterstützung :grin:

**Comment by Aris-t2** [comment]
True, that was a hard nut to crack. :-)

I'm glad I could help.
