### ISSUE TITLE
Wrong detection DirectX - WDDM2

### ISSUE THREAD

**Issue by avicodec** [builtbybel/ReadySunValley#8]
I have a Radeon RX 570 with last AMD drivers, DirectX 12 and WDDM 2.7 and I have Error "DirectX too low" and WDDM2 not at the minimum ... (which is false) WhyNotWin11 is ok
[DxDiag.txt](https://github.com/builtbybel/ReadySunValley/files/6758439/DxDiag.txt)

**Comment by AcrylicShrimp** [comment]
Same here with NVIDIA Geforce RTX 3080 Ti.

![image](https://user-images.githubusercontent.com/19178575/124360619-bf0c6400-dc65-11eb-9954-3da5e355fea1.png)

**Comment by Belim** [comment]
:thinking: the code is crude since the contents of dxdiag are only extracted into an xml file and contain methods query DirectXVersion and DriverModel 

here again an even simpler version which now exports to text file :smile:
[ReadySunValley_x64.zip](https://github.com/builtbybel/ReadySunValley/files/6758766/ReadySunValley_x64.zip)

**Comment by AcrylicShrimp** [comment]
@Belim The version you attached is running without any issue! Thank you for your hard work :)

![image](https://user-images.githubusercontent.com/19178575/124362223-a0f73180-dc6e-11eb-85da-8e8674d463a6.png)

**Comment by Belim** [comment]
Damn whyyy :smile: but its to slowww :unamused: 
how many seconds did the directx/wddm check take?

can you please check again with the previous/official version but delete this time the `dxv.xml` file in the execution dir of ReadySunValley.exe

**Comment by Belim** [comment]
what about this one? it also export to dxv.xml
[ReadySunValley.zip](https://github.com/builtbybel/ReadySunValley/files/6758774/ReadySunValley.zip)

**Comment by AcrylicShrimp** [comment]
@Belim Well, I think they are almost same; they took around 10 seconds. And I don't know why but the official release also worked after re-download and launch it.

**Comment by Belim** [comment]
@AcrylicShrimp thanks, let us stay with this "fixed" version. it also seems to me the safer variant

**Comment by nebula-neru** [comment]
i also get this :/
![image](https://user-images.githubusercontent.com/65756037/124365766-ed0a8d80-dbfe-11eb-99b7-ce7b1e65dbec.png)

**Comment by Belim** [comment]
did you try the latest release 0.11.12

**Comment by nebula-neru** [comment]
yes that is latest.

**Comment by Belim** [comment]
check the latest release https://github.com/builtbybel/ReadySunValley/releases
