### ISSUE TITLE
marked as trojan

### ISSUE THREAD

**Issue by ghoffman9** [builtbybel/ReadySunValley#9]
windows defender detects as trojan today:
Script/Wacatac.B!ml

**Comment by Belim** [comment]
after every update the defender hits because the file is simply new. 
Of course its clean https://www.virustotal.com/gui/file/0897d5850e619a92794b6aa2d61e09a1113646aa577fe8f9ff5fa5bc10847532/detection
Wait a few hours an you'll see it will not be flagged anymore
